# 4 Take numbers from user and display by using sets
s = set()

n = int(input("Enter an element: "))
s.add(n)
n = int(input("Enter an element: "))
s.add(n)
n = int(input("Enter an element: "))
s.add(n)
n = int(input("Enter an element: "))
s.add(n)
n = int(input("Enter an element: "))
s.add(n)
n = int(input("Enter an element: "))
s.add(n)
n = int(input("Enter an element: "))
s.add(n)
n = int(input("Enter an element: "))
s.add(n)
n = int(input("Enter an element: "))
s.add(n)
print(s)